# Generated by Django 4.0.2 on 2022-02-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('enrollment', models.CharField(max_length=8, verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Automovil',
                'verbose_name_plural': 'Automoviles',
                'ordering': ['id'],
            },
        ),
    ]
