# Generated by Django 4.0.2 on 2022-02-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titular Vehiculo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='enrollment',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
