# Generated by Django 4.0.2 on 2022-02-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_color_car_model_car_owner_alter_car_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
    ]
